<?php
require_once 'marytrans_core.api.inc';
require_once 'marytrans_core.forms.inc';

/**
 * Implements hook_menu().
 */
function marytrans_core_menu() {
    $items = [];
    $items['home'] = [
        'title' => 'Home',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'marytrans_core_home',
        'access callback' => TRUE,
    ];
    $items['faq'] = [
        'title' => 'FAQ',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'marytrans_core_faq',
        'access callback' => TRUE,
    ];
    $items['my-orders'] = [
        'title' => 'My orders',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'marytrans_core_my_orders',
        'access callback' => 'user_is_logged_in',
    ];
    $items['prices_and_fees'] = [
        'title' => 'Prices & Fees',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'marytrans_core_prices_and_fees',
        'access callback' => TRUE,
    ];

    return $items;
}

/**
 * Implements hook_block_info().
 */
function marytrans_core_block_info() {
    $blocks = [];
    $blocks['marytrans_fast_calculator'] = [
        'info' => t('MaryTrans fast calculator'),
        'status' => 0,
    ];
    $blocks['marytrans_order_steps'] = [
        'info' => t('MaryTrans order steps'),
        'status' => 0,
    ];
    $blocks['marytrans_check_our_cars'] = [
        'info' => t('MaryTrans check our cars'),
        'status' => 0,
    ];
    $blocks['marytrans_testimonials'] = [
        'info' => t('MaryTrans testimonials'),
        'status' => 0,
    ];
    $blocks['marytrans_short_contacts'] = [
        'info' => t('MaryTrans short contacts'),
        'status' => 0,
    ];
    $blocks['marytrans_faq'] = [
        'info' => t('MaryTrans FAQ'),
        'status' => 0,
    ];
    $blocks['marytrans_what_we_offer'] = [
        'info' => t('MaryTrans what we offer'),
        'status' => 0,
    ];
    $blocks['marytrans_my_orders'] = [
        'info' => t('MaryTrans my orders'),
        'status' => 0,
    ];
    $blocks['marytrans_order_car'] = [
        'info' => t('MaryTrans order car'),
        'status' => 0,
    ];
    $blocks['marytrans_order_more_details'] = [
        'info' => t('MaryTrans order more details'),
        'status' => 0,
    ];
    $blocks['marytrans_prices_and_fees'] = [
        'info' => t('MaryTrans prices and fees'),
        'status' => 0,
    ];

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function marytrans_core_block_view($delta = '') {
    global $language;

    $block = [];
    $variables = [];
    $path_to_theme = base_path() . drupal_get_path('theme', 'mary_trans');

    switch ($delta) {
        case 'marytrans_fast_calculator':
            $variables['path_to_theme'] = $path_to_theme;
            $block['content'] = theme('marytrans_fast_calculator', $variables);
            break;
        case 'marytrans_order_steps':
            $variables['path_to_theme'] = $path_to_theme;
            $block['content'] = theme('marytrans_order_steps', $variables);
            break;
        case 'marytrans_check_our_cars':
            $cars = db_select('node', 'n')
                ->fields('n')
                ->condition('type', 'car')
                ->condition('status', '1')
                ->execute()
                ->fetchAllAssoc('nid');
            $cars = node_load_multiple(array_keys($cars));
            $variables = [
                'path_to_theme' => $path_to_theme,
                'cars' => $cars,
            ];
            $block['content'] = theme('marytrans_check_our_cars', $variables);
            break;
        case 'marytrans_testimonials':
            $testimonials = db_select('node', 'n')
                ->fields('n')
                ->condition('type', 'testimonials')
                ->condition('status', '1')
                ->condition('language', [
                    $language->language,
                    LANGUAGE_NONE,
                ], 'IN')
                ->execute()
                ->fetchAllAssoc('nid');
            $testimonials = node_load_multiple(array_keys($testimonials));
            $variables = [
                'path_to_theme' => $path_to_theme,
                'testimonials' => $testimonials,
            ];
            $block['content'] = theme('marytrans_testimonials', $variables);
            break;
        case 'marytrans_short_contacts':
            $variables['path_to_theme'] = $path_to_theme;
            $block['content'] = theme('marytrans_short_contacts', $variables);
            break;
        case 'marytrans_faq':
            $questions = db_select('node', 'n')
                ->fields('n')
                ->condition('type', 'faq')
                ->condition('status', '1')
                ->condition('language', [
                    $language->language,
                    LANGUAGE_NONE,
                ], 'IN')
                ->execute()
                ->fetchAllAssoc('nid');
            $questions = node_load_multiple(array_keys($questions));
            $variables = [
                'path_to_theme' => $path_to_theme,
                'questions' => $questions,
                'form' => $form = drupal_get_form('marytrans_core_ask_question_form'),
            ];
            $block['content'] = theme('marytrans_faq', $variables);
            break;
        case 'marytrans_what_we_offer':
            $offers = db_select('node', 'n')
                ->fields('n')
                ->condition('type', 'what_we_offer')
                ->condition('status', '1')
                ->condition('language', [
                    $language->language,
                    LANGUAGE_NONE,
                ], 'IN')
                ->execute()
                ->fetchAllAssoc('nid');
            $offers = node_load_multiple(array_keys($offers));
            $variables = [
                'path_to_theme' => $path_to_theme,
                'offers' => $offers,
            ];
            $block['content'] = theme('marytrans_what_we_offer', $variables);
            break;
        case 'marytrans_my_orders':
            global $user;
            $query = db_select('node', 'n')
                ->fields('n')
                ->condition('type', 'order');

            if (!in_array('administrator', $user->roles)) {
                $query->condition('uid', $user->uid);
            }

            $orders = $query->condition('status', '1')
                ->execute()
                ->fetchAllAssoc('nid');
            $orders = node_load_multiple(array_keys($orders));
            $variables = [
                'path_to_theme' => $path_to_theme,
                'orders' => $orders,
            ];
            $block['content'] = theme('marytrans_my_orders', $variables);
            break;
        case 'marytrans_order_car':
            $variables = [
                'path_to_theme' => $path_to_theme,
                'form' => drupal_get_form('marytrans_core_order_car_form')
            ];
            $block['content'] = theme('marytrans_order_car', $variables);
            break;
        case 'marytrans_order_more_details':
            $variables = [];
            $block['content'] = theme('marytrans_order_more_details', $variables);
            break;
        case 'marytrans_prices_and_fees':
            $variables = [
                'path_to_theme' => $path_to_theme,
            ];
            $block['content'] = theme('marytrans_prices_and_fees', $variables);
            break;
    }

    return $block;
}

/**
 * Implements hook_theme().
 */
function marytrans_core_theme() {
    return [
        'marytrans_fast_calculator' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_fast_calculator',
        ],
        'marytrans_order_steps' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_order_steps',
        ],
        'marytrans_check_our_cars' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_check_our_cars',
        ],
        'marytrans_testimonials' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_testimonials',
        ],
        'marytrans_short_contacts' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_short_contacts',
        ],
        'marytrans_faq' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_faq',
        ],
        'marytrans_what_we_offer' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_what_we_offer',
        ],
        'marytrans_my_orders' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_my_orders',
        ],
        'marytrans_order_car' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_order_car',
        ],
        'marytrans_order_more_details' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_order_more_details',
        ],
        'marytrans_prices_and_fees' => [
            'variables' => ['vars' => NULL],
            'template' => 'templates/marytrans_prices_and_fees',
        ],
    ];
}